spring:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_SERVER_PORT}/eureka/
