name: AntCamp Config Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check YAML files
        run: |
          echo "Checking config files..."
          find . -name "*.yml" -o -name "*.yaml"